import dotenv from 'dotenv'; 
import swaggerJSDoc from 'swagger-jsdoc';
dotenv.config();


const port: number = parseInt(process.env.PORT || '3000', 10);  

const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Your API Documentation',
      version: '1.0.0',
      description: 'API documentation generated by Swagger',
    },
    servers: [
      {
        url: `http://localhost:${port}`, 
      },
    ],
  },
  apis: ['./src/routes/*.ts', './src/controllers/*.ts'], 
};

const swaggerSpec = swaggerJSDoc(swaggerOptions);

export default swaggerSpec;
